[package]
name = "lockless"
version = "0.1.0"
authors = ["aceeri (conmcclusk@gmail.com)"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
specs = "0.11.0-alpha5"
shred = "0.7.0-alpha5"
nphysics3d = { git = "https://github.com/sebcrozet/nphysics" }
machinae = { git = "https://github.com/rustgd/machinae", commit = "450ad44c89405ad687b38896e779fb33380b406b" }
rayon = "*"
