[package]
name = "util"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.1"
lazy_static = "1.3.0"

